# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr: none

jobs:
  - job: "BuildAzureDevOpsAgent"
    displayName: "Build Azure DevOps Agent"
    pool: dockeragent
    variables:
     - name: AGENT_VERSION
       value: '2.200.2'
     - name: TARGETARCH
       value: 'amd64'
    

    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker Connection'
          command: 'login'

      - task: Bash@3
        displayName: 'docker build'
        inputs:
          targetType: 'inline'
          script: |
            VERSION_TAG=`git describe --always --abbrev=7`
            docker build -t pickonefish/azure-devops-agent:$(AGENT_VERSION)-$(TARGETARCH).$(VERSION_TAG) --build-arg AGENT_VERSION=$(AGENT_VERSION) --build-arg TARGETARCH=$(TARGETARCH) .
            docker push pickonefish/azure-devops-agent:$(AGENT_VERSION)-$(TARGETARCH).$(VERSION_TAG)
        condition: succeededOrFailed()
