version: "3"
services:
  azure_devops_agent_1:
    container_name: azure_devops_agent_1
    image: pickonefish/azure-devops-agent:2.210.1-amd64.81d3cd4
    environment:
      - AZP_URL=
      - AZP_TOKEN=
      - AZP_AGENT_NAME=azure_devops_agent_1
      - AZP_POOL=dockeragent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/user/.m2:/root/.m2
      - /home/user/.docker:/root/.docker
